spring:
  application:
    name: hello-spring-cloud-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084
  main:
    allow-bean-definition-overriding: true
server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




